name: Deploy CloudFormation

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Target stack to deploy (base/lambda/rds)'
        required: true
        default: 'base'
      environment:
        description: 'Environment tag value'
        required: false
        default: 'Dev'
      aws-region:
        description: 'AWS Region'
        required: false
        default: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Select stack template
        id: select_stack
        run: |
          case "${{ github.event.inputs.stack }}" in
            base) TEMPLATE="cfn/base_stack.yml"; PARAMS="cfn/parameters/base_params.json" ;;
            lambda) TEMPLATE="cfn/lambda_stack.yml"; PARAMS="cfn/parameters/lambda_params.json" ;;
            rds) TEMPLATE="cfn/rds_stack.yml"; PARAMS="cfn/parameters/rds_params.json" ;;
            *) echo "Invalid stack selected"; exit 1 ;;
          esac
          echo "TEMPLATE=$TEMPLATE" >> $GITHUB_ENV
          echo "PARAMS=$PARAMS" >> $GITHUB_ENV
          echo "STACK_NAME=${{ github.event.inputs.stack }}-stack" >> $GITHUB_ENV

      - name: Deploy stack
        run: |
          bash scripts/deploy_stack.sh "$STACK_NAME" "$TEMPLATE" "$PARAMS" "Environment=${{ github.event.inputs.environment }}"
